name: Jen Murphy, PhD Student
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

twitter_username:     jendmurphy
github_username:      jendmurphy
linkedin_username:    jendmurphy
facebook_username:    jendmurphy
